name: PowerShell script
author: Pooya Kharamesh
inputs:
  eventId:
    description: The event Id of the initiating workflow
    required: true
  telemetryScopeJson:
    description: Telemetry scope generated during the workflow initialization
    required: true
runs:
  using: composite
  steps:
    - run: try { ${{ github.action_path }}/WorkflowPostProcess.ps1 -eventId '${{ inputs.eventId }}' -telemetryScopeJson '${{ inputs.telemetryScopeJson }}' } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
      shell: PowerShell
branding:
  icon: terminal
  color: blue
